import type { ScaffoldOptions, TemplateFile } from "../types.js";

export const TS_TSCONFIG: TemplateFile = {
  path: "tsconfig.json",
  contents: JSON.stringify(
    {
      compilerOptions: {
        target: "ES2022",
        module: "ESNext",
        moduleResolution: "Bundler",
        strict: true,
        esModuleInterop: true,
        skipLibCheck: true,
        declaration: false,
        outDir: "dist",
      },
      include: ["src/**/*"],
    },
    null,
    2,
  ) + "\n",
};

export function packageJson(opts: ScaffoldOptions, deps: Record<string, string> = {}): TemplateFile {
  const isTs = opts.language === "typescript";
  return {
    path: "package.json",
    contents: JSON.stringify(
      {
        name: opts.name,
        version: "0.1.0",
        private: true,
        type: "module",
        main: isTs ? "dist/index.js" : "src/index.js",
        scripts: {
          start: isTs ? "node dist/index.js" : "node src/index.js",
          ...(isTs ? { build: "tsc", dev: "tsx watch src/index.ts" } : {}),
        },
        dependencies: {
          "@modelcontextprotocol/sdk": "^1.0.0",
          zod: "^3.22.4",
          ...deps,
        },
        ...(isTs
          ? {
              devDependencies: {
                "@types/node": "^20.11.0",
                tsx: "^4.7.0",
                typescript: "^5.4.0",
              },
            }
          : {}),
      },
      null,
      2,
    ) + "\n",
  };
}

export function gitignore(): TemplateFile {
  return {
    path: ".gitignore",
    contents: ["node_modules", "dist", ".env", "*.log", ".DS_Store", ""].join("\n"),
  };
}

export function envExample(vars: { name: string; description: string }[]): TemplateFile {
  const lines = [
    "# Environment variables for this MCP server",
    ...vars.map((v) => `${v.name}=  # ${v.description}`),
    "",
  ];
  return { path: ".env.example", contents: lines.join("\n") };
}

export function authMiddleware(opts: ScaffoldOptions): string {
  if (!opts.auth) return "";
  return `
function requireAuth(extra: { request?: { headers?: Record<string, string> } }): void {
  const expected = process.env.MCP_API_KEY;
  if (!expected) return;
  const provided = extra.request?.headers?.["x-api-key"];
  if (provided !== expected) throw new Error("Unauthorized");
}
`.trim();
}

export function readme(opts: ScaffoldOptions, extra: string): TemplateFile {
  const bin = opts.language === "typescript" ? "node dist/index.js" : "node src/index.js";
  const cmd = opts.transport === "stdio" ? bin : `${bin} --port 8080`;
  return {
    path: "README.md",
    contents: `# ${opts.name}

An MCP server scaffolded by \`create-mcp-server\`.

## Run

\`\`\`bash
cp .env.example .env
# fill in values
npm install
${opts.language === "typescript" ? "npm run build\n" : ""}npm start
\`\`\`

## Claude Desktop config

\`\`\`json
{
  "mcpServers": {
    "${opts.name}": {
      "command": "${bin.split(" ")[0]}",
      "args": ${JSON.stringify(bin.split(" ").slice(1))},
      "env": {}
    }
  }
}
\`\`\`

${extra}

> Generated by \`create-mcp-server\`. Replace this README with your own.
`,
  };
}
