export type OpenAPIV3 = {
  openapi?: string;
  paths?: Record<
    string,
    Partial<{
      get: Op;
      post: Op;
      put: Op;
      patch: Op;
      delete: Op;
    }>
  >;
};

type Op = { operationId?: string; summary?: string };

function safeFnName(s: string): string {
  const x = s.replace(/[^a-zA-Z0-9_]/g, "_");
  return /^[a-zA-Z_]/.test(x) ? x : `op_${x}`;
}

function joinUrl(base: string, path: string): string {
  const b = base.replace(/\/$/, "");
  const p = path.startsWith("/") ? path : `/${path}`;
  return `${b}${p}`;
}

/** Minimal fetch-based TS client for OpenAPI path keys. */
export function generateSdkSource(spec: OpenAPIV3, opts?: { className?: string }): string {
  const cls = opts?.className ?? "ApiClient";
  const lines: string[] = [
    "/** Auto-generated by @mr-aftab-ahmad-khan/sdkforge — review before ship. */",
    `export class ${cls} {`,
    "  constructor(private readonly baseUrl: string) {}",
  ];

  const paths = spec.paths ?? {};
  for (const [path, methods] of Object.entries(paths)) {
    for (const method of ["get", "post", "put", "patch", "delete"] as const) {
      const op = methods?.[method];
      if (!op) continue;
      const id = op.operationId ?? `${method}_${path}`;
      const fn = safeFnName(id);
      const METHOD = method.toUpperCase();
      lines.push(
        `  ${fn}(init?: RequestInit): Promise<Response> { const u = new URL(${JSON.stringify(path)}, this.baseUrl).toString(); return fetch(u, { method: ${JSON.stringify(METHOD)}, ...init }); }`,
      );
    }
  }

  lines.push("}");
  return lines.join("\n");
}

export { joinUrl };
