import type { Typepress } from "./router.js";
import type { RouteDescriptor } from "./types.js";
import type { SchemaDescriptor } from "./schema.js";

export function generateTypescriptClient(
  typepress: Typepress,
  options: { className?: string; baseUrlVar?: string } = {},
): string {
  const className = options.className ?? "ApiClient";
  const routes = typepress.list();
  const types: string[] = [];
  const methods: string[] = [];
  const seenNames = new Set<string>();

  for (const route of routes) {
    const name = methodName(route);
    if (seenNames.has(name)) continue;
    seenNames.add(name);
    const inputType = buildInputType(route, name, types);
    const outputType = buildOutputType(route, name, types);
    methods.push(buildMethod(route, name, inputType, outputType));
  }

  return [
    `// Auto-generated by typepress. Do not edit by hand.`,
    `export interface ClientOptions { baseUrl: string; fetch?: typeof fetch; headers?: Record<string, string>; }`,
    `export interface ApiError { code: string; message: string; field?: string; status: number; }`,
    "",
    types.join("\n\n"),
    "",
    `export class ${className} {`,
    `  private readonly baseUrl: string;`,
    `  private readonly _fetch: typeof fetch;`,
    `  private readonly headers: Record<string, string>;`,
    `  constructor(options: ClientOptions) {`,
    `    this.baseUrl = options.baseUrl.replace(/\\/$/, "");`,
    `    this._fetch = options.fetch ?? fetch;`,
    `    this.headers = options.headers ?? {};`,
    `  }`,
    methods.join("\n\n"),
    `}`,
  ].join("\n");
}

function methodName(route: RouteDescriptor): string {
  const path = route.path
    .split("/")
    .filter(Boolean)
    .map((p) => p.startsWith(":") ? `By${capitalize(p.slice(1))}` : capitalize(p))
    .join("");
  return route.method + (path || "Root");
}

function capitalize(s: string): string {
  return s.charAt(0).toUpperCase() + s.slice(1);
}

function buildInputType(route: RouteDescriptor, name: string, types: string[]): string | undefined {
  const parts: string[] = [];
  if (route.params) parts.push(`params: ${schemaToTs(route.params)}`);
  if (route.query) parts.push(`query: ${schemaToTs(route.query)}`);
  if (route.body) parts.push(`body: ${schemaToTs(route.body)}`);
  if (parts.length === 0) return undefined;
  const typeName = `${capitalize(name)}Input`;
  types.push(`export interface ${typeName} { ${parts.join("; ")} }`);
  return typeName;
}

function buildOutputType(route: RouteDescriptor, name: string, types: string[]): string {
  if (!route.response) return "unknown";
  const typeName = `${capitalize(name)}Output`;
  types.push(`export type ${typeName} = ${schemaToTs(route.response)};`);
  return typeName;
}

function buildMethod(route: RouteDescriptor, name: string, input: string | undefined, output: string): string {
  const wantsInput = Boolean(input);
  const sig = wantsInput ? `(input: ${input})` : "()";
  const body: string[] = [];
  body.push(`    let url = this.baseUrl + ${JSON.stringify(route.path)};`);
  if (route.params) {
    body.push(`    for (const [k, v] of Object.entries((input as { params: Record<string, unknown> }).params)) {`);
    body.push(`      url = url.replace(\`:\${k}\`, encodeURIComponent(String(v)));`);
    body.push(`    }`);
  }
  if (route.query) {
    body.push(`    const _qs = new URLSearchParams();`);
    body.push(`    for (const [k, v] of Object.entries((input as { query: Record<string, unknown> }).query)) {`);
    body.push(`      if (v !== undefined && v !== null) _qs.append(k, String(v));`);
    body.push(`    }`);
    body.push(`    const _qsStr = _qs.toString();`);
    body.push(`    if (_qsStr) url += "?" + _qsStr;`);
  }
  body.push(`    const _res = await this._fetch(url, {`);
  body.push(`      method: ${JSON.stringify(route.method.toUpperCase())},`);
  body.push(`      headers: { "content-type": "application/json", ...this.headers },`);
  if (route.body) {
    body.push(`      body: JSON.stringify((input as { body: unknown }).body),`);
  }
  body.push(`    });`);
  body.push(`    if (!_res.ok) {`);
  body.push(`      const err = await _res.json().catch(() => ({})) as { error?: ApiError };`);
  body.push(`      throw Object.assign(new Error(err?.error?.message ?? _res.statusText), { code: err?.error?.code ?? "HTTP_ERROR", status: _res.status });`);
  body.push(`    }`);
  body.push(`    if (_res.status === 204) return undefined as unknown as ${output};`);
  body.push(`    return (await _res.json()) as ${output};`);
  return `  async ${name}${sig}: Promise<${output}> {\n${body.join("\n")}\n  }`;
}

export function schemaToTs(descriptor: SchemaDescriptor): string {
  switch (descriptor.type) {
    case "string": return "string";
    case "number": return "number";
    case "boolean": return "boolean";
    case "literal":
      return typeof descriptor.value === "string" ? JSON.stringify(descriptor.value) : String(descriptor.value);
    case "enum": return descriptor.values.map((v) => JSON.stringify(v)).join(" | ");
    case "array": return `Array<${schemaToTs(descriptor.items)}>`;
    case "object": {
      const fields = Object.entries(descriptor.properties).map(([k, v]) => {
        const opt = descriptor.required.includes(k) ? "" : "?";
        return `${JSON.stringify(k)}${opt}: ${schemaToTs(v)}`;
      });
      return `{ ${fields.join("; ")} }`;
    }
    case "optional": return `${schemaToTs(descriptor.inner)} | undefined`;
    case "union": return descriptor.options.map(schemaToTs).join(" | ");
    case "null": return "null";
    case "unknown":
    default: return "unknown";
  }
}
