#!/usr/bin/env node
import { existsSync, writeFileSync } from "node:fs";
import { pathToFileURL } from "node:url";
import { resolve } from "node:path";
import { loadDotenv } from "./dotenv.js";
import { EnvValidationError } from "./errors.js";
import type { ZodTypeAny } from "zod";

interface CliOptions {
  schema: string;
  envFile: string;
  out?: string;
}

function parseArgs(argv: string[]): { command: string; opts: CliOptions } {
  const command = argv[0] ?? "help";
  const opts: CliOptions = {
    schema: "src/env.ts",
    envFile: ".env",
  };
  for (let i = 1; i < argv.length; i++) {
    const arg = argv[i];
    if (arg === "--schema" || arg === "-s") {
      const next = argv[++i];
      if (next) opts.schema = next;
    } else if (arg === "--env" || arg === "-e") {
      const next = argv[++i];
      if (next) opts.envFile = next;
    } else if (arg === "--out" || arg === "-o") {
      const next = argv[++i];
      if (next) opts.out = next;
    } else if (arg === "-h" || arg === "--help") {
      return { command: "help", opts };
    }
  }
  return { command, opts };
}

interface LoadedSchema {
  server: Record<string, ZodTypeAny>;
  client: Record<string, ZodTypeAny>;
}

async function loadSchemaModule(path: string): Promise<LoadedSchema> {
  const abs = resolve(process.cwd(), path);
  if (!existsSync(abs)) {
    throw new Error(`Schema file not found: ${abs}`);
  }
  const mod = await import(pathToFileURL(abs).href);
  const schema = (mod.schema ?? mod.default ?? mod) as Partial<LoadedSchema>;
  return {
    server: schema.server ?? {},
    client: schema.client ?? {},
  };
}

function placeholderFor(schema: ZodTypeAny): string {
  const def = (schema as { _def?: { defaultValue?: () => unknown } })._def;
  if (def?.defaultValue) {
    try {
      const v = def.defaultValue();
      if (v !== undefined) return String(v);
    } catch {
      // ignore
    }
  }
  const desc = (schema as { description?: string }).description;
  if (desc) return desc;
  const name = (schema as { _def?: { typeName?: string } })._def?.typeName ?? "";
  if (name.includes("Number")) return "0";
  if (name.includes("Boolean")) return "false";
  if (name.includes("Url")) return "https://example.com";
  return "your-value-here";
}

async function runValidate(opts: CliOptions): Promise<number> {
  const schema = await loadSchemaModule(opts.schema);
  const envFromFile = loadDotenv(resolve(process.cwd(), opts.envFile));
  const runtime: Record<string, string | undefined> = {
    ...process.env,
    ...envFromFile,
  };
  const invalid: { name: string; received: unknown; message: string }[] = [];

  for (const [name, s] of Object.entries({ ...schema.server, ...schema.client })) {
    const value = runtime[name] === "" ? undefined : runtime[name];
    const r = s.safeParse(value);
    if (!r.success) {
      for (const issue of r.error.issues) {
        invalid.push({ name, received: value, message: issue.message });
      }
    }
  }

  if (invalid.length === 0) {
    process.stdout.write(`envy: ${Object.keys(schema.server).length + Object.keys(schema.client).length} env vars OK\n`);
    return 0;
  }
  process.stderr.write(`envy: ${invalid.length} invalid env var${invalid.length === 1 ? "" : "s"}\n`);
  for (const v of invalid) {
    const got = v.received === undefined ? "<missing>" : JSON.stringify(v.received);
    process.stderr.write(`  - ${v.name}: ${v.message} (received: ${got})\n`);
  }
  return 1;
}

async function runGenerateExample(opts: CliOptions): Promise<number> {
  const schema = await loadSchemaModule(opts.schema);
  const lines: string[] = ["# Generated by `envy generate-example`", ""];
  if (Object.keys(schema.server).length > 0) {
    lines.push("# --- server-only ---");
    for (const [name, s] of Object.entries(schema.server)) {
      lines.push(`${name}=${placeholderFor(s)}`);
    }
    lines.push("");
  }
  if (Object.keys(schema.client).length > 0) {
    lines.push("# --- exposed to client ---");
    for (const [name, s] of Object.entries(schema.client)) {
      lines.push(`${name}=${placeholderFor(s)}`);
    }
    lines.push("");
  }
  const out = opts.out ?? ".env.example";
  writeFileSync(resolve(process.cwd(), out), lines.join("\n"), "utf8");
  process.stdout.write(`envy: wrote ${out}\n`);
  return 0;
}

function printHelp() {
  process.stdout.write(`envy <command>

Commands:
  validate          Validate the current environment against the schema
  generate-example  Generate a .env.example from the schema

Options:
  --schema, -s   Path to the schema module (default: src/env.ts)
  --env, -e      Path to the .env file (default: .env)
  --out, -o      Output file for generate-example (default: .env.example)
  --help, -h     Show this help

The schema module must export { server, client } as Zod record(s).
Example:
  // src/env.ts
  import { z } from "zod";
  export const schema = {
    server: { DATABASE_URL: z.string().url() },
    client: {},
  };
`);
}

async function main() {
  const argv = process.argv.slice(2);
  const { command, opts } = parseArgs(argv);
  try {
    switch (command) {
      case "validate":
        process.exit(await runValidate(opts));
        break;
      case "generate-example":
        process.exit(await runGenerateExample(opts));
        break;
      case "help":
      case "--help":
      case "-h":
        printHelp();
        process.exit(0);
        break;
      default:
        process.stderr.write(`envy: unknown command "${command}"\n`);
        printHelp();
        process.exit(1);
    }
  } catch (err) {
    if (err instanceof EnvValidationError) {
      process.stderr.write(`${err.message}\n`);
    } else if (err instanceof Error) {
      process.stderr.write(`envy: ${err.message}\n`);
    } else {
      process.stderr.write(`envy: unknown error\n`);
    }
    process.exit(1);
  }
}

main();
